# -*- coding: utf-8 -*-
"""desiciontree

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PH4Oe3Kq7_tHtdcqSnJ5uFmbLvT1RIQ6
"""

!pip install streamlit

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,confusion_matrix,roc_auc_score,roc_curve
from sklearn import tree

##load data
data=pd.read_csv('/content/Heart_Disease_Dataset.csv')
data.head()

data.tail()

#information about columns
data.info()

data.shape

#statstical analysis
data.describe()

#checking null values
data.isnull().sum()

#duplicates
data.duplicated().sum()

data.duplicated()

data.columns

for column in data.columns:
  print(f'{column}:{data[column].unique()}')

for column in data.columns:
  print(data[column].value_counts())

#one hot encoding
data=pd.get_dummies(data,columns=['Diabetic'],drop_first=True)
data.head()

#convert binary categorical variables into numerical columns
binary_cols=['Sex','Smoking','AlcoholDrinking','PhysicalActivity','Asthma','KidneyDisease','SkinCancer']
for col in binary_cols:
  data[col]=data[col].map({'Yes':1,'No':0})