# -*- coding: utf-8 -*-
"""day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFPKqmDg2nEGe5KMy72wEvP7QDumteeH
"""

n = int(input("Enter a positive integer: "))
sum_even = 0

for i in range(1, n + 1):
    if i % 2 == 0:
        sum_even += i

print("Sum of all even numbers between 1 and", n, "is:", sum_even)

